# Configuration for pullapprove.com
#
# Approval access and primary role is determined by info in the project ownership spreadsheet:
# https://docs.google.com/spreadsheets/d/1oTGX-keDOVNLOmMNIn3IGMvinTrIojSZXWI2dnXkGmQ/edit#gid=0
#
# === GitHub username to Full name map ===
#
# andrewseguin - Andrew Seguin
# crisbeto - Kristiyan Kostadinov
# devversion - Paul Gschwendtner
# jelbourn - Jeremy Elbourn
# josephperrott - Joey Perrott
# kara - Kara Erickson
# mmalerba - Miles Malerba
# tinayuangao - Tina Gao

version: 2

group_defaults:
  required: 1
  reset_on_reopened:
    enabled: true
  approve_by_comment:
    enabled: false

groups:
  # If no other groups apply, we at least require approval from a core member
  fallback:
    conditions:
      files:
        - '*'
    users:
      - andrewseguin
      - crisbeto
      - devversion
      - jelbourn
      - josephperrott
      - kara
      - mmalerba
      - tinayuangao

  tools-and-config:
    conditions:
      files:
        - 'scripts/*'
        - 'test/*'
        - 'tools/*'
    users:
      - devversion # primary
      - jelbourn

  cdk:
    conditions:
      files:
        - 'src/cdk/*'
    users:
      - jelbourn # primary
      - mmalerba

  autocomplete:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/autocomplete/*'
        - 'src/material-examples/autocomplete-*'
    users:
      - kara # primary
      - jelbourn

  button:
    conditions:
      files:
        include:
          - 'src/(demo-app|e2e-app|lib)/button/*'
          - 'src/material-examples/button-*'
        exclude:
          - 'src/material-examples/button-toggle-*'
    users:
      - tinayuangao # primary
      - jelbourn

  button-toggle:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/button-toggle/*'
        - 'src/material-examples/button-toggle-*'
    users:
      - tinayuangao # primary
      - jelbourn

  card:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/card/*'
        - 'src/material-examples/card-*'
    users:
      - kara # primary
      - jelbourn

  checkbox:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/checkbox/*'
        - 'src/material-examples/checkbox-*'
    users:
      - tinayuangao # primary
      - jelbourn

  chips:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/chips/*'
        - 'src/material-examples/chips-*'
    users:
      - tinayuangao # primary
      - jelbourn

  data-table:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/table/*'
        - 'src/lib/core/table/*'
        - 'src/material-examples/table-*'
    users:
      - andrewseguin # primary
      - jelbourn

  datepicker:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/datepicker/*'
        - 'src/lib/core/datetime/*'
        - 'src/material-examples/datepicker-*'
    users:
      - mmalerba # primary
      - jelbourn

  dialog:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/dialog/*'
        - 'src/material-examples/dialog-*'
    users:
      - jelbourn # primary
      - mmalerba

  expansion:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/expansion/*'
        - 'src/material-examples/expansion-*'
    users:
      - josephperrott # primary
      - jelbourn

  grid-list:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/grid-list/*'
        - 'src/material-examples/grid-list-*'
    users:
      - kara # primary
      - jelbourn

  icon:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/icon/*'
        - 'src/material-examples/icon-*'
    users:
      - jelbourn # primary
      - mmalerba

  input:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/input/*'
        - 'src/material-examples/input-*'
    users:
      - mmalerba # primary
      - jelbourn

  list:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/list/*'
        - 'src/material-examples/list-*'
    users:
      - kara # primary
      - jelbourn

  menu:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/menu/*'
        - 'src/material-examples/menu-*'
    users:
      - kara # primary
      - jelbourn

  overlay:
    conditions:
      files:
        - 'src/(demo-app|e2e-app)/overlay/*'
        - 'src/lib/core/overlay/*'
        - 'src/material-examples/overlay-*'
    users:
      - jelbourn # primary
      - crisbeto

  portal:
    conditions:
      files:
        - 'src/(demo-app|e2e-app)/portal/*'
        - 'src/lib/core/portal/*'
        - 'src/material-examples/portal-*'
    users:
      - jelbourn # primary
      - mmalerba

  progress:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/progress-(bar|spinner)/*'
        - 'src/material-examples/progress-(bar|spinner)-*'
    users:
      - josephperrott # primary
      - jelbourn

  radio:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/radio/*'
        - 'src/material-examples/radio-*'
    users:
      - tinayuangao # primary
      - jelbourn

  ripple:
    conditions:
      files:
        - 'src/(demo-app|e2e-app)/ripple/*'
        - 'src/lib/core/ripple/*'
        - 'src/material-examples/ripple-*'
    users:
      - devversion # primary
      - jelbourn

  select:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/select/*'
        - 'src/material-examples/select-*'
    users:
      - kara # primary
      - jelbourn

  sidenav:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/sidenav/*'
        - 'src/material-examples/sidenav-*'
    users:
      - mmalerba # primary
      - jelbourn

  slide-toggle:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/slide-toggle/*'
        - 'src/material-examples/slide-toggle-*'
    users:
      - devversion # primary
      - jelbourn

  slider:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/slider/*'
        - 'src/material-examples/slider-*'
    users:
      - mmalerba # primary
      - jelbourn

  snack-bar:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/snack-bar/*'
        - 'src/material-examples/snack-bar-*'
    users:
      - jelbourn # primary
      - mmalerba

  tabs:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/tabs/*'
        - 'src/material-examples/tabs-*'
    users:
      - andrewseguin # primary
      - jelbourn

  toolbar:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/toolbar/*'
        - 'src/material-examples/toolbar-*'
    users:
      - devversion # primary
      - jelbourn

  tooltip:
    conditions:
      files:
        - 'src/(demo-app|e2e-app|lib)/tooltip/*'
        - 'src/material-examples/tooltip-*'
    users:
      - andrewseguin # primary
      - jelbourn

  typography:
    conditions:
      files:
        - 'src/(demo-app|e2e-app)/typography/*'
        - 'src/lib/core/typography/*'
        - 'src/material-examples/typography-*'
    users:
      - crisbeto # primary
      - jelbourn
